"""initial schema

Revision ID: 7934a61cf82d
Revises: 
Create Date: 2026-08-24 00:46:40.056050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7934a61cf82d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_weakness_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('wrong_question_id', sa.Integer(), nullable=True),
    sa.Column('limit_n', sa.Integer(), nullable=False),
    sa.Column('scope_note', sa.String(length=255), nullable=True),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('source_items', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_weakness_analyses_username'), 'learning_weakness_analyses', ['username'], unique=False)
    op.create_index(op.f('ix_learning_weakness_analyses_wrong_question_id'), 'learning_weakness_analyses', ['wrong_question_id'], unique=False)
    op.create_table('question_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_id'), 'activity_logs', ['resource_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', name='assignmentstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_access_requests_requester_id'), 'bank_access_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_bank_access_requests_status'), 'bank_access_requests', ['status'], unique=False)
    op.create_table('knowledge_lesson_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point', sa.String(length=128), nullable=False),
    sa.Column('weakness_analysis_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['weakness_analysis_id'], ['learning_weakness_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_lesson_analyses_knowledge_point'), 'knowledge_lesson_analyses', ['knowledge_point'], unique=False)
    op.create_index(op.f('ix_knowledge_lesson_analyses_weakness_analysis_id'), 'knowledge_lesson_analyses', ['weakness_analysis_id'], unique=False)
    op.create_index('ix_knowledge_lesson_point_weakness', 'knowledge_lesson_analyses', ['knowledge_point', 'weakness_analysis_id'], unique=False)
    op.create_table('wrong_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('wrong_answer', sa.JSON(), nullable=False),
    sa.Column('question_type_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('ingest_source', sa.Enum('ocr', 'manual', 'dify', name='ingestsource'), nullable=False),
    sa.Column('external_trace_id', sa.String(length=255), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_payload', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('wrong_at', sa.DateTime(), nullable=True),
    sa.Column('review_status', sa.Enum('not_reviewed', 'reviewed', 'mastered', name='reviewstatus'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_trace_id')
    )
    op.create_index(op.f('ix_wrong_questions_created_by'), 'wrong_questions', ['created_by'], unique=False)
    op.create_index(op.f('ix_wrong_questions_id'), 'wrong_questions', ['id'], unique=False)
    op.create_table('assignment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('wrong_question_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['wrong_question_id'], ['wrong_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_questions_assignment_id'), 'assignment_questions', ['assignment_id'], unique=False)
    op.create_table('practice_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wrong_question_id', sa.Integer(), nullable=False),
    sa.Column('generated_question', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wrong_question_id'], ['wrong_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wrong_question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.JSON(), nullable=False),
    sa.Column('standard_answer', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wrong_question_id'], ['wrong_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answers_assignment_id'), 'user_answers', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    op.create_table('user_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'submitted', 'graded', name='userassignmentstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assignments_assignment_id'), 'user_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_user_assignments_user_id'), 'user_assignments', ['user_id'], unique=False)
    op.create_table('wrong_question_knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wrong_question_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_tag_id'], ['knowledge_tags.id'], ),
    sa.ForeignKeyConstraint(['wrong_question_id'], ['wrong_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrong_question_knowledge_tags')
    op.drop_index(op.f('ix_user_assignments_user_id'), table_name='user_assignments')
    op.drop_index(op.f('ix_user_assignments_assignment_id'), table_name='user_assignments')
    op.drop_table('user_assignments')
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_assignment_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_table('practice_records')
    op.drop_index(op.f('ix_assignment_questions_assignment_id'), table_name='assignment_questions')
    op.drop_table('assignment_questions')
    op.drop_index(op.f('ix_wrong_questions_id'), table_name='wrong_questions')
    op.drop_index(op.f('ix_wrong_questions_created_by'), table_name='wrong_questions')
    op.drop_table('wrong_questions')
    op.drop_index('ix_knowledge_lesson_point_weakness', table_name='knowledge_lesson_analyses')
    op.drop_index(op.f('ix_knowledge_lesson_analyses_weakness_analysis_id'), table_name='knowledge_lesson_analyses')
    op.drop_index(op.f('ix_knowledge_lesson_analyses_knowledge_point'), table_name='knowledge_lesson_analyses')
    op.drop_table('knowledge_lesson_analyses')
    op.drop_index(op.f('ix_bank_access_requests_status'), table_name='bank_access_requests')
    op.drop_index(op.f('ix_bank_access_requests_requester_id'), table_name='bank_access_requests')
    op.drop_table('bank_access_requests')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_activity_logs_resource_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('question_types')
    op.drop_index(op.f('ix_learning_weakness_analyses_wrong_question_id'), table_name='learning_weakness_analyses')
    op.drop_index(op.f('ix_learning_weakness_analyses_username'), table_name='learning_weakness_analyses')
    op.drop_table('learning_weakness_analyses')
    op.drop_table('knowledge_tags')
    op.execute('DROP TYPE IF EXISTS assignmentstatus')
    op.execute('DROP TYPE IF EXISTS ingestsource')
    op.execute('DROP TYPE IF EXISTS reviewstatus')
    op.execute('DROP TYPE IF EXISTS userassignmentstatus')
    # ### end Alembic commands ###
